server:
  port: 9095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/showin
    username: postgres
    password: AnisMohamadi5651$
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: false

minio:
  bucket:
    name: plc
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin
  url:  http://127.0.0.1:9000




